# Generated by Django 2.1.7 on 2019-05-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='amount',
            new_name='balance',
        ),
    ]
