# Generated by Django 2.1.7 on 2019-05-07 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190507_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
