# Generated by Django 2.1.7 on 2019-05-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190507_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
