# Generated by Django 2.1.7 on 2019-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DW', '0003_auto_20190507_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
