# Generated by Django 2.1.7 on 2019-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DW', '0005_auto_20190508_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
